name: dispatch
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        type: choice
        options:
          - info
          - warning
          - debug
        default: warning
      environment:
        description: "Environment"
        type: environment
      matrix:
        description: "Matrix strategy as JSON string"
        required: true
        type: string
jobs:
  log-the-inputs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJSON(inputs.matrix) }}
    steps:
      - name: Print strategy values
        run: |
          echo "Log level: $LEVEL"
          echo "Environment: $ENVIRONMENT"
          echo "Version: ${{ matrix.version }}"
          echo "OS: ${{ matrix.os }}"
        env:
          LEVEL: ${{ inputs.logLevel }}
          ENVIRONMENT: ${{ inputs.environment }}
